import Providers from "@/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <meta
          name="viewpoint"
          content="width=device-width, initial-scale=1.0"
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
