// components
import Navbar from "@/layouts/_main/navbar";
import UserTopBar from "@/layouts/_main/topbar";
import ActionBar from "@/layouts/_main/actionbar";
import ActionBar from "@/layouts/_main/footer";
import { Toolbar } from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <UserTopBar />
      <Navbar />
      <ActionBar />
      {children}
      <Toolbar sx={{ display: { xs: "block", md: "none" } }} />
      <Footer />
    </>
  );
}
