import UserTopBar from "@/layouts/_main/topbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <UserTopBar />
      {children}
    </>
  );
}
